name: carla

on:
  push:
    paths:
    - 'carla/0.9.12-no-rendering/**'
    - '.github/workflows/carla-0.9.12-no-rendering.yml' # Self-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_CONTAINER_IMAGES_USERNAME }}" -p "${{ secrets.DOCKERHUB_CONTAINER_IMAGES_TOKEN }}"
    - name: Push image to DockerHub
      run: |
        docker build -t doganulus/carla:0.9.12-no-rendering carla/0.9.12-no-rendering
        docker push doganulus/carla:0.9.12-no-rendering
