name: carla-0.9.13-no-rendering

on:
  push:
    paths:
    - 'carla/0.9.13-no-rendering/**'
    - '.github/workflows/carla-0.9.13-no-rendering.yml' # Self-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the image
      run:  docker build -t docker.io/doganulus/carla:0.9.13-no-rendering carla/0.9.13-no-rendering
    - name: Push the image to DockerHub
      run: |
        docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
        docker push docker.io/doganulus/carla:0.9.13-no-rendering
